DROP SEQUENCE SOMSEQ;
DROP TABLE SOMBOARD;

CREATE SEQUENCE SOMSEQ;

-- 번호, 이름, 제목, 내용, 날짜 

CREATE TABLE SOMBOARD(
	SNUM NUMBER PRIMARY KEY,
	SNAME VARCHAR2(1000) NOT NULL,
	STITLE VARCHAR2(2000) NOT NULL,
	SCONTENT VARCHAR2(4000) NOT NULL,
	SDATE DATE NOT NULL
);



INSERT INTO SOMBOARD
VALUES(SOMSEQ.NEXTVAL,'관리자','TEST요','어려워!!!!!!!!!!!!!!',SYSDATE);

SELECT SNUM,SNAME, STITLE,SCONTENT,SDATE
FROM SOMBOARD;