DROP SEQUENCE BOARDNOSEQ;
DROP SEQUENCE GROUPNOSEQ;

DROP TABLE ANSWERBOARD;

CREATE SEQUENCE BOARDNOSEQ; 	--글 번호
CREATE SEQUENCE GROUPNOSEQ;		--그룹번호

--글번호 그룹번호 그룹순서 제목탭 제목 내용 작성자 작성일

CREATE TABLE ANSWERBOARD(
	BOARDNO NUMBER PRIMARY KEY,
	GROUPNO NUMBER NOT NULL,
	GROUPSEQ NUMBER NOT NULL,	--부모 +1	/ 중간에 답변이 달리면 부모의 글번호 이후의 글을 다 1씩 올려주고 INSERT해야한다
	TITLETAB NUMBER NOT NULL,	--들여쓰기 기능 / 부모 +1
	TITLE VARCHAR2(500) NOT NULL,
	CONTENT VARCHAR2(4000) NOT NULL,
	WRITER VARCHAR2(100) NOT NULL,
	REGDATE DATE NOT NULL
);

SELECT * FROM ANSWERBOARD ORDER BY GROUPNO DESC, GROUPSEQ;

--첫번째 글 작성
INSERT INTO ANSWERBOARD
VALUES(BOARDNOSEQ.NEXTVAL, GROUPNOSEQ.NEXTVAL,1,0,'1번글입니다','1번글 내용입니다','관리자',SYSDATE);

--두번째 글 작성
INSERT INTO ANSWERBOARD
VALUES(BOARDNOSEQ.NEXTVAL, GROUPNOSEQ.NEXTVAL,1,0,'2번글입니다','2번글 내용입니다','학생1',SYSDATE);

--1번글입니다(글번호1번)에 답변달기
--UPDATE : 부모의 글과 같은 그룹번호, 부모의 그룹순서보다 더 큰 그룹순서
--			그룹순서를 +1
UPDATE ANSWERBOARD 
SET GROUPSEQ = GROUPSEQ +1
WHERE GROUPNO =(SELECT GROUPNO FROM ANSWERBOARD WHERE BOARDNO =1)
AND GROUPSEQ > (SELECT GROUPSEQ FROM ANSWERBOARD WHERE BOARDNO =1)

INSERT INTO ANSWERBOARD
VALUES(
	BOARDNOSEQ.NEXTVAL,
	(SELECT GROUPNO FROM ANSWERBOARD WHERE BOARDNO=1),
	(SELECT GROUPSEQ FROM ANSWERBOARD WHERE BOARDNO = 1)+1,
	(SELECT TITLETAB FROM ANSWERBOARD WHERE BOARDNO = 1)+1,
	'RE:1번글입니다',
	'1번글에 답변달기',
	'학생',
	SYSDATE
);

--RE:1번글입니다(글번호3)에 답변달기
--UPDATE :부모와 같은 그룹번호, 부모의 그룹순서보다 더 큰 그룹순서인 글 들을 찾아서 그룹순서+1

UPDATE ANSWERBOARD 
SET GROUPSEQ = GROUPSEQ +1
WHERE GROUPNO =(SELECT GROUPNO FROM ANSWERBOARD WHERE BOARDNO =3)
AND GROUPSEQ > (SELECT GROUPSEQ FROM ANSWERBOARD WHERE BOARDNO =3)

INSERT INTO ANSWERBOARD
VALUES(
	BOARDNOSEQ.NEXTVAL,
	(SELECT GROUPNO from ANSWERBOARD WHERE BOARDNO=3),
	(SELECT GROUPSEQ FROM ANSWERBOARD WHERE BOARDNO=3)+1,
	(SELECT TITLETAB FROM ANSWERBOARD WHERE BOARDNO=3)+1,
	'RE:RE:1번글입니다',
	'3번글에 답변달기',
	'학생4',
	SYSDATE
);

--글번호 1번에 대한 답변달기
UPDATE ANSWERBOARD
SET GROUPSEQ = GROUPSEQ+1
WHERE GROUPNO =(SELECT GROUPNO FROM ANSWERBOARD WHERE BOARDNO=1)
AND GROUPSEQ > (SELECT GROUPSEQ FROM ANSWERBOARD WHERE BOARDNO=1)


INSERT INTO ANSWERBOARD
VALUES(
	BOARDNOSEQ.NEXTVAL,
	(SELECT GROUPNO FROM ANSWERBOARD WHERE BOARDNO=1),
	(SELECT GROUPSEQ FROM ANSWERBOARD WHERE BOARDNO=1)+1,
	(SELECT TITLETAB FROM ANSWERBOARD WHERE BOARDNO =1)+1,
	'RE:1번글입닌다',
	'1번글에 또다른 답변',
	'???',
	SYSDATE
);

--글번호 1번에 답글의 또 다른 답글 (5번) 달기

UPDATE ANSWERBOARD
SET GROUPSEQ = GROUPSEQ+1
WHERE GROUPNO = (SELECT GROUPNO FROM ANSWERBOARD WHERE BOARDNO=5)
AND GROUPSEQ > (SELECT GROUPSEQ FROM ANSWERBOARD WHERE BOARDNO=5)

INSERT INTO ANSWERBOARD
VALUES(
	BOARDNOSEQ.NEXTVAL,
	(SELECT GROUPNO FROM ANSWERBOARD WHERE BOARDNO=5),
	(SELECT GROUPSEQ FROM ANSWERBOARD WHERE BOARDNO=5)+1,
	(SELECT TITLETAB FROM ANSWERBOARD WHERE BOARDNO=5)+1,
	'RE:RE:1번글입니다',
	'1번글 답변-답변',
	'몰라',
	SYSDATE
);














