CREATE TABLE BOARD(
	BOARD_ID NUMBER(5) NOT NULL,
	MEM_ID VARCHAR2(30) NOT NULL,
	BOARD_TITLE VARCHAR2(200) NOT NULL,
	BOARD_CONTENT VARCHAR2(1024) NOT NULL,
	BOARD_READCNT NUMBER(10),
	BOARD_REGDATE DATE,
	BOARD_IMG VARCHAR2(1000),
	BOARD_CATEGORY NUMBER(3) NOT NULL,
CONSTRAINT BOARD_PK_BOARD_ID PRIMARY KEY (BOARD_ID),
CONSTRAINT BOARD_FK_MEM_ID FOREIGN KEY (MEM_ID) REFERENCES MEMBER(MEM_ID)
);
